import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import agentsRouter from "./agents";
import schemesRouter from "./schemes";
import debtorsRouter from "./debtors";
import mattersRouter from "./matters";
import documentsRouter from "./documents";
import paymentsRouter from "./payments";
import tasksRouter from "./tasks";
import reportsRouter from "./reports";
import publicRouter from "./public";
import postingCodesRouter from "./posting-codes";
import transactionsRouter from "./transactions";
import creditorsRouter from "./creditors";
import requisitionsRouter from "./requisitions";
import communicationsRouter from "./communications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(agentsRouter);
router.use(schemesRouter);
router.use(debtorsRouter);
router.use(mattersRouter);
router.use(documentsRouter);
router.use(paymentsRouter);
router.use(tasksRouter);
router.use(postingCodesRouter);
router.use(transactionsRouter);
router.use(creditorsRouter);
router.use(requisitionsRouter);
router.use(communicationsRouter);
router.use(reportsRouter);
router.use(publicRouter);

export default router;
